from setuptools import setup

setup(
    name="pendulum",
    version="0.1",
    packages=['src'],
    install_requires=[
        'aiohttp',
        'aiosignal',
        'async-timeout',
        'attrs',
        'cffi',
        'charset-normalizer',
        'discord.py',
        'python-dotenv',
        'frozenlist',
        'geographiclib',
        'python-dateutil',
        'h3',
        'idna',
        'multidict',
        'numpy',
        'pycparser',
        'pytz',
        'pytest',
        'pytest-cov',
        'pytest-mock',
        'requests',
        'timezonefinder',
        'wcwidth',
        'yarl'
    ]
)
