from enum import StrEnum

class weatherCodes(StrEnum):
    s0 = 'Clear sky :sunny:'
    s1 = 'Mainly clear :white_sun_small_cloud:'
    s2 = 'Partly cloudy :white_sun_cloud:'
    s3 = 'Overcast :cloud:'
    s45 = 'Fog :fog:'
    s48 = 'Depositing rime fog :fog:'
    s51 = 'Drizzle Light :white_sun_rain_cloud:'
    s53 = 'Drizzle moderate :white_sun_rain_cloud:'
    s55 = 'Drizzle dense :white_sun_rain_cloud:'
    s56 = 'Freezing Drizzle Light :white_sun_rain_cloud:'
    s57 = 'Freezing Drizzle dense :white_sun_rain_cloud:'
    s61 = 'Rain Slight :cloud_rain:'
    s63 = 'Rain moderate :cloud_rain:'
    s65 = 'Rain heavy :thunder_cloud_rain:'
    s66 = 'Freezing Rain Light :cloud_rain:'
    s67 = 'Freezing Rain heavy :cloud_rain:'
    s71 = 'Snow fall Slight :cloud_snow:'
    s73 = 'Snow fall moderate :cloud_snow:'
    s75 = 'Snow fall heavy :cloud_snow:'
    s77 = 'Snow grains :snowflake:'
    s80 = 'Rain showers Slight :cloud_rain:'
    s81 = 'Rain showers moderate :cloud_rain:'
    s82 = 'Rain showers violent :thunder_cloud_rain:'
    s85 = 'Snow showers slight :cloud_snow:'
    s86 = 'Snow showers heavy :cloud_snow:'
    s95 = 'Thunderstorm Slight or moderate :thunder_cloud_rain:'
    s96 = 'Thunderstorm with slight hail :thunder_cloud_rain:'
    s99 = 'Thunderstorm with heavy hail :thunder_cloud_rain:'