
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test
      run: echo "$TOKEN"
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        allow-prereleases: true
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install .
    - name: Create .env
      run: |
        touch .env
        echo TOKEN=${{ secrets.API_KEY }} >> .env
        cat .env
<<<<<<< HEAD
    - name: Run Unit Test with PyTest
      run: |
        pytest
=======
        echo "ls -a ."
        ls -a .
>>>>>>> 5ecb41e (test)
    - name: Bot Run Test
      run:
        python run.py
        