
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  TOKEN: ${{ secrets.API_KEY }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test
      run: echo "$TOKEN"
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        allow-prereleases: true
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install .
    - name: Bot Run Test
      env: #an environment variable
        TOKEN: ${{ secrets.API_KEY }}
      run:
        python run.py
        